version: '3.7'

services:
  app:
    build: .
    container_name: phpS4
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - "8281:80"
    environment:
      - SSL_MODE=off
