#docker-compose up --build -d && docker-compose exec app /bin/bash
version: '3.7'

services:
  app:
    build: .
    container_name: phpS4
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - "8282:80"
    environment:
      - SSL_MODE=off
