version: '3.7'

services:
  app:
    build: .
    container_name: phpS4
    restart: always
    volumes:
      - ./pages:/var/www/html # Это позволит вам редактировать файлы локально
    ports:
      - "8281:80"
    environment:
      - SSL_MODE=off
